[package]
name = "serde_xml"
version = "0.6.0"
authors = ["Oliver Schneider <serde-xml98198@oli-obk.de>"]
license = "MIT non-military non-spy"
description = "xml support for rust-serde"
repository = "https://github.com/serde-rs/xml"

[dependencies]
serde = "0.6"
log = "0.3"

[dev-dependencies]
serde_macros = "0.5"
